"""sentiment table

Revision ID: 1ccb0f9448f2
Revises: d3bf7acf01f1
Create Date: 2019-05-10 11:11:47.407185

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1ccb0f9448f2'
down_revision = 'd3bf7acf01f1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sentiment',
    sa.Column('reviewId', sa.Integer(), nullable=False),
    sa.Column('reviewText', sa.String(length=5000), nullable=True),
    sa.Column('sentiment', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('reviewId')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('sentiment')
    # ### end Alembic commands ###
