"""movie table

Revision ID: 69651866c1ed
Revises: c4c75aa78e3e
Create Date: 2019-04-28 16:53:26.972715

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '69651866c1ed'
down_revision = 'c4c75aa78e3e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('movie',
    sa.Column('movieId', sa.Integer(), nullable=False),
    sa.Column('imdbId', sa.Integer(), nullable=True),
    sa.Column('tmdbId', sa.Integer(), nullable=True),
    sa.Column('title', sa.Text(), nullable=True),
    sa.Column('tagline', sa.Text(), nullable=True),
    sa.Column('genres', sa.Text(), nullable=True),
    sa.Column('overview', sa.Text(), nullable=True),
    sa.Column('poster_path', sa.Text(), nullable=True),
    sa.Column('runtime', sa.Float(), nullable=True),
    sa.Column('release_date', sa.Date(), nullable=True),
    sa.Column('budget', sa.Integer(), nullable=True),
    sa.Column('revenue', sa.Float(), nullable=True),
    sa.Column('popularity', sa.Float(), nullable=True),
    sa.Column('vote_average', sa.Float(), nullable=True),
    sa.Column('vote_count', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('movieId')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('movie')
    # ### end Alembic commands ###
